/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        /* ── Design System semantic tokens (mapeia CSS vars) ── */
        bg:               "var(--bg)",
        surface:          "var(--surface)",
        "surface-alt":    "var(--surface-alt)",
        border:           "var(--border)",
        "border-strong":  "var(--border-strong)",
        text:             "var(--text)",
        "text-dim":       "var(--text-dim)",
        "text-faint":     "var(--text-faint)",
        accent:           "var(--accent)",
        "accent-hover":   "var(--accent-hover)",
        success:          "var(--success)",
        warning:          "var(--warning)",
        danger:           "var(--danger)",

        /* ── Product tokens (company identity) ── */
        "color-resibag":   "var(--color-resibag)",
        "color-industria": "var(--color-industria)",

        /* ── Semantic extras ── */
        amber:            "var(--amber)",
        "amber-bg":       "var(--amber-bg)",

        /* ── Legacy aliases (mantidos para views existentes — remover na Fase 1) ── */
        primary:          "#b5000b",
        "primary-container": "#e30613",
        "primary-fixed":  "#ffdad5",
        "primary-fixed-dim": "#ffb4aa",
        "on-primary":     "#ffffff",
        "on-primary-container": "#fff5f3",
        secondary:        "#5c5f60",
        "secondary-container": "#e1e3e4",
        "on-secondary":   "#ffffff",
        "on-secondary-container": "#626566",
        tertiary:         "#0059a8",
        "tertiary-container": "#0071d4",
        "on-tertiary":    "#ffffff",
        "on-tertiary-container": "#f5f7ff",
        "surface-white":  "#FFFFFF",
        "surface-bright": "#fff8f7",
        "surface-dim":    "#e4d7d7",
        "surface-container": "#f8ebea",
        "surface-container-low":    "#fef1f0",
        "surface-container-high":   "#f2e5e5",
        "surface-container-highest": "#ede0df",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#ede0df",
        "surface-tint":   "#c0000c",
        "on-surface":     "#201a1a",
        "on-surface-variant": "#5e3f3b",
        "inverse-surface": "#362f2f",
        "inverse-on-surface": "#fbeeed",
        "border-subtle":  "#E5E7EB",
        outline:          "#936e69",
        "outline-variant": "#e9bcb6",
        "gray-text":      "#6B7280",
        error:            "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error":       "#ffffff",
        "danger-dark":    "#C7212B",
      },
      borderRadius: {
        none:    "0",
        sm:      "var(--radius-sm)",
        DEFAULT: "var(--radius-sm)",
        md:      "var(--radius-sm)",
        lg:      "var(--radius-md)",
        xl:      "10px",
        "2xl":   "12px",
        "3xl":   "16px",
        full:    "9999px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
      },
      spacing: {
        "touch":   "48px",
        "sidebar": "288px",
        "topbar":  "64px",
      },
    },
  },
  plugins: [],
};
