export const COMPANIES = {
  all: {
    id: "all",
    name: "Visão Grupo",
    short: "Grupo Sanwey",
    primary: "#2D3436",
    dark: "#1A1D1E",
    light: "#EDEEEF",
    active: "#4D5456",
    accent: "#2D3436",
    description: "Visão consolidada de todas as empresas do Grupo",
  },
  resibag: {
    id: "resibag",
    name: "Resibag",
    short: "Resibag",
    primary: "#1A6E35",
    dark: "#0F4A23",
    light: "#E8F2EC",
    active: "#2D9B52",
    accent: "#1A6E35",
    description: "Big bags homologados para resíduos perigosos (Classe I, filtrante, verde)",
    focus: "Compliance ambiental",
  },
  comercial: {
    id: "comercial",
    name: "Sanwey Comercial",
    short: "Comercial",
    primary: "#1E4D8C",
    dark: "#0F2A52",
    light: "#E6EDF7",
    active: "#2F6BBF",
    accent: "#1E4D8C",
    description: "Comercialização de Sanbags para múltiplos setores industriais",
    focus: "Vendas B2B consultivas",
  },
  industria: {
    id: "industria",
    name: "Sanwey Indústria",
    short: "Indústria",
    primary: "#8C3A1E",
    dark: "#5A230F",
    light: "#F7ECE6",
    active: "#BF5430",
    accent: "#8C3A1E",
    description: "Fabricação de Sanbags e contentores flexíveis — atende carteira B2B complexa",
    focus: "Fabricação e parceria técnica",
  },
  montemor: {
    id: "montemor",
    name: "Sanwey Monte Mor",
    short: "Monte Mor",
    primary: "#6B4E1E",
    dark: "#3E2D10",
    light: "#F5EFE2",
    active: "#A37830",
    accent: "#6B4E1E",
    description: "Produção de tecidos, linhas, alças e big bags simples",
    focus: "Matéria-prima e linha de entrada",
  },
};

export const NEUTRAL = {
  graphite: "#2D3436",
  slate: "#636E72",
  warmWhite: "#FAFAF8",
  lightGray: "#F5F5F3",
  gold: "#C49B2A",
  amber: "#D4730E",
  red: "#CC2936",
  success: "#2D9B52",
};

export const COMPANY_IDS = ["comercial", "industria", "resibag", "montemor"];
